### ISSUE TITLE
ngx-bookings: does not download and automatically switch to an updated version of the frontend

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#3]
Transferred from Jira: https://acaprojects.atlassian.net/browse/PTT-140

ngx-bookings: does not download and automatically switch to an updated version of the frontend

Confirmed always replicatable in latest prod build of ngx-bookings deployed at kpmg, when endpoints are both windows chrome and iPads.

The frontend regularly downloads `ngsw.json?ngsw-cache-bust=<number>` and then download `favicon.ico?ngx-cache-bust=<number>` but then download download any other assests.

**Comment by MrYuion** [comment]
@w-le, is this still an issue with the latest builds?

**Comment by w-le** [comment]
it was resolved for that client by december, for that specific ngx-bookings frontends.

but I believe the bookings app has been rewritten since then.
so I don't know whether the new version has the issue.

so imo close this issue, and it can be raised as a new one if we come across the same behaviour while testing the new bookings frontend
